openapi: "3.0.2"

info:
  title: "FLUG Service API"
  version: "0.1.0"
  description: "A service API for the Fyns Linux User Group website"
  contact:
    name: "Fyns Linux User Group"
    url: "https://flug.dk/"
  license:
    name: "GNU Affero General Public License v3.0"
    url: "https://www.gnu.org/licenses/"

servers:
  - url: "http://localhost:2000/"
    description: "Local server"

tags:
  - name: Gets
    description: "Get a list of resources"
  - name: Get
    description: "Get a resource"
  - name: Create
    description: "Create a new resource"
  - name: Update
    description: "Update a resource"
  - name: Delete
    description: "Delete a resource"

paths:
  /users:
    get:
      operationId: getUsers
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/max"
        - $ref: "#/components/parameters/initialLetterUser"
        - $ref: "#/components/parameters/orderUser"
      tags:
        - Gets
      summary: "Retrieve list of users"
      description: "Returns a list of users"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Users"
        "400":
          description: "Response when query parameters (max, initial_letter, or order) are incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when a list does not exist"
          $ref: "#/components/responses/NotFound"

    post:
      operationId: createUser
      tags:
        - Create
      summary: Create a new user
      description: Creates a new user and initiates a password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPostBody"
      responses:
        "201":
          description: "Response on success"
          $ref: "#/components/responses/User"
        "400":
          description: "Response when the request body object is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"

  /users/{uid}:
    parameters:
      - $ref: "#/components/parameters/uid"

    get:
      operationId: getUser
      tags:
        - Get
      summary: "Retrieve a specific user"
      description: "Retrieves details of a specific user by ID"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/User"
        "400":
          description: "Response when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    patch:
      operationId: updateUser
      tags:
        - Update
      summary: "Update user details"
      description: "Updates the details of a specific user by ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserPatchBody"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/User"
        "400":
          description: "Response when the request body object or uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteUser
      tags:
        - Delete
      summary: "Delete a user"
      description: "Removes a specific user from the system by ID"
      responses:
        "204":
          description: "Response on success delete"
          $ref: "#/components/responses/SuccessfulDelete"
        "400":
          description: "Response when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

  /blogs:
    get:
      operationId: getBlogs
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/max"
        - $ref: "#/components/parameters/initialLetterBlog"
        - $ref: "#/components/parameters/orderBlog"
      tags:
        - Gets
      summary: "Retrieve list of blog posts"
      description: "Returns a list of blog posts"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Blogs"
        "400":
          description: "Response when query parameters (max, initial_letter, or order) are incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when a list does not exist"
          $ref: "#/components/responses/NotFound"

    post:
      operationId: createBlog
      tags:
        - Create
      summary: "Create a new blog post"
      description: "Creates a new blog post"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogPostBody"
      responses:
        "201":
          description: "Response on success"
          $ref: "#/components/responses/Blog"
        "400":
          description: "Response when the request body object is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"

  /blogs/{id}:
    parameters:
      - $ref: "#/components/parameters/uidOrSlug"

    get:
      operationId: getBlog
      tags:
        - Get
      summary: "Retrieve a specific blog post"
      description: "Retrieves details of a specific blog post by ID"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Blog"
        "400":
          description: "Response when the uid or slug is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid or slug is not found"
          $ref: "#/components/responses/NotFound"

  /blogs/{uid}:
    parameters:
      - $ref: "#/components/parameters/uid"

    patch:
      operationId: updateBlog
      tags:
        - Update
      summary: "Update blog post details"
      description: "Updates the details of a specific blog post by ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BlogPatchBody"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Blog"
        "400":
          description: "Response when the request body object or uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteBlog
      tags:
        - Delete
      summary: "Delete a blog post"
      description: "Removes a specific blog post from the system by ID"
      responses:
        "204":
          description: "Response on success delete"
          $ref: "#/components/responses/SuccessfulDelete"
        "400":
          description: "Response when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

  /events:
    get:
      operationId: getEvents
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/max"
        - $ref: "#/components/parameters/initialLetterEvent"
        - $ref: "#/components/parameters/orderEvent"
      tags:
        - Gets
      summary: "Retrieve list of events"
      description: "Returns a list of events"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Events"
        "400":
          description: "Response when query parameters (max, initial_letter, or order) are incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when a list does not exist"
          $ref: "#/components/responses/NotFound"

    post:
      operationId: createEvent
      tags:
        - Create
      summary: "Create a new event"
      description: "Creates a new event"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventPostBody"
      responses:
        "201":
          description: "Response on success"
          $ref: "#/components/responses/Event"
        "400":
          description: "Response when the request body object is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"

  /events/{id}:
    parameters:
      - $ref: "#/components/parameters/uidOrSlug"

    get:
      operationId: getEvent
      tags:
        - Get
      summary: "Retrieve a specific event"
      description: "Retrieves details of a specific event by ID"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Event"
        "400":
          description: "Response when the uid or slug is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid or slug is not found"
          $ref: "#/components/responses/NotFound"

  /events/{uid}:
    parameters:
      - $ref: "#/components/parameters/uid"

    patch:
      operationId: updateEvent
      tags:
        - Update
      summary: "Update event details"
      description: "Updates the details of a specific event by ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventPatchBody"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Event"
        "400":
          description: "Response when the request body object or uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteEvent
      tags:
        - Delete
      summary: "Delete a event"
      description: "Removes a specific event from the system by ID"
      responses:
        "204":
          description: "Response on success delete"
          $ref: "#/components/responses/SuccessfulDelete"
        "400":
          description: "Response when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

  /images:
    get:
      operationId: getImages
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/max"
        - $ref: "#/components/parameters/initialLetterImage"
        - $ref: "#/components/parameters/orderImage"
      tags:
        - Gets
      summary: "Retrieve list of images"
      description: "Returns a list of images"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Images"
        "400":
          description: "Response when query parameters (max, or order) are incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when a list does not exist"
          $ref: "#/components/responses/NotFound"

    post:
      operationId: createImage
      tags:
        - Create
      summary: "Create a new image"
      description: "Creates a new image"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImagePostBody"
      responses:
        "201":
          description: "Response on success"
          $ref: "#/components/responses/Image"
        "400":
          description: "Response when the request body object is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"

  /images/{uid}:
    parameters:
      - $ref: "#/components/parameters/uid"

    get:
      operationId: getImage
      tags:
        - Get
      summary: "Retrieve a specific image"
      description: "Retrieves details of a specific image by ID"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Image"
        "400":
          description: "Response when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    patch:
      operationId: updateImage
      tags:
        - Update
      summary: "Update image details"
      description: "Updates the details of a specific image by ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ImagePatchBody"
      responses:
        "200":
          description: "Response on success"
          $ref: "#/components/responses/Image"
        "400":
          description: "Response when the request body object or uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Response when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Response when the uid is not found"
          $ref: "#/components/responses/NotFound"

    delete:
      operationId: deleteImage
      tags:
        - Delete
      summary: "Delete a image"
      description: "Removes a specific image from the system by ID"
      responses:
        "204":
          description: "Response on success delete"
          $ref: "#/components/responses/SuccessfulDelete"
        "400":
          description: "Returned when the uid is incorrect"
          $ref: "#/components/responses/BadRequest"
        "401":
          description: "Returned when the request is not authenticated"
          $ref: "#/components/responses/Unauthorized"
        "404":
          description: "Returned when the uid is not found"
          $ref: "#/components/responses/NotFound"

components:
  parameters:
    uid:
      name: uid
      in: path
      required: true
      description: UID of the resource to retrieve or modify
      schema:
        type: integer
        format: int64

    uidOrSlug:
      name: id
      in: path
      required: true
      description: UID or SLUG of the resource to retrieve or modify
      schema:
        oneOf:
          - type: integer
            format: int64
          - type: string
            pattern: "^(?!-)[a-z0-9-]+(?<!-)$"

    page:
      name: page
      in: query
      description: Specifies the page number for paginated results.
      required: false
      schema:
        type: integer
        default: 1

    max:
      name: max
      in: query
      description: Specifies the maximum number of items per page.
      required: false
      schema:
        type: integer
        default: 100

    initialLetterUser:
      name: initial_letter
      in: query
      description: Filters fistName by the initial letter.
      required: false
      schema:
        type: string
        enum:
          [
            "all",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "other",
          ]
        default: all

    initialLetterBlog:
      name: initial_letter
      in: query
      description: Filters title by the initial letter.
      required: false
      schema:
        type: string
        enum:
          [
            "all",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "other",
          ]
        default: all

    initialLetterEvent:
      name: initial_letter
      in: query
      description: Filters title by the initial letter.
      required: false
      schema:
        type: string
        enum:
          [
            "all",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "other",
          ]
        default: all

    initialLetterImage:
      name: initial_letter
      in: query
      description: Filters src by the initial letter.
      required: false
      schema:
        type: string
        enum:
          [
            "all",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "other",
          ]
        default: all

    orderUser:
      name: order
      in: query
      description: "Specifies the field to sort the results."
      required: false
      schema:
        type: string
        enum: [firstname, lastname, email, createdat, updatedat, loggedinat]
        default: firstname

    orderBlog:
      name: order
      in: query
      description: "Specifies the field to sort the results."
      required: false
      schema:
        type: string
        enum: [title, createdat, updatedat]
        default: title

    orderEvent:
      name: order
      in: query
      description: "Specifies the field to sort the results."
      required: false
      schema:
        type: string
        enum: [title, createdat, updatedat]
        default: title

    orderImage:
      name: order
      in: query
      description: "Specifies the field to sort the results."
      required: false
      schema:
        type: string
        enum: [src, createdat, updatedat]
        default: src

  responses:
    Users:
      description: "Returns a list of users on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    allOf:
                      - $ref: "#/components/schemas/GetResources"
                      - properties:
                          items:
                            items:
                              $ref: "#/components/schemas/UserItem"
          example:
            success: true
            data:
              items:
                - uid: 1
                  firstName: "John"
                  lastName: "Doe"
                  email: "john.doe@example.com"
                  createdAt: "2023-11-28T09:00:00Z"
                  updatedAt: "2023-11-28T09:30:00Z"
                  loggedInAt: "2023-11-28T09:30:00Z"
                - uid: 2
                  firstName: "Jane"
                  lastName: "Smith"
                  email: "jane.smith@example.com"
                  createdAt: "2023-11-29T08:00:00Z"
                  updatedAt: "2023-11-29T08:45:00Z"
                  loggedInAt: "2023-11-29T08:45:00Z"
              pagination:
                first: 1
                prev: 1
                current: 1
                next: 1
                last: 1
              results: 2
              totalResults: 2
              page: 1
              totalPages: 1
            message: "Successfully retrieved the resource."

    User:
      description: "Return the user on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    $ref: "#/components/schemas/User"
          example:
            success: true
            data:
              uid: 1
              firstName: "John"
              lastName: "Doe"
              email: "john.doe@example.com"
              createdAt: "2023-11-28T09:00:00Z"
              updatedAt: "2023-11-28T09:30:00Z"
              loggedInAt: "2023-11-28T09:30:00Z"
            message: "{fix me; The message will be different based on the methods, Get, Post and Pacth}"

    Blogs:
      description: "Returns a list of blog posts on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    allOf:
                      - $ref: "#/components/schemas/GetResources"
                      - properties:
                          items:
                            items:
                              $ref: "#/components/schemas/BlogItem"
          example:
            success: true
            data:
              items:
                - uid: 1
                  title: "Blog Post 1"
                  shortDesc: "A brief description of the blog post 1"
                  image:
                    src: "image1.jpg"
                    alt: "Image for blog post 1"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
                  _links:
                    self:
                      href: "/blogs/1"
                      title: "Read More"
                    slug:
                      href: "/blogs/blog-post-1"
                      title: "Read More"
                - uid: 2
                  title: "Blog Post 2"
                  shortDesc: "A brief description of the blog post 2"
                  image:
                    src: "image2.jpg"
                    alt: "Image for blog post 2"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
                  _links:
                    self:
                      href: "/blogs/2"
                      title: "Read More"
                    slug:
                      href: "/blogs/blog-post-2"
                      title: "Read More"
              pagination:
                first: null
                prev: null
                self:
                  href: "/blogs?page=1"
                  title: "Current page"
                next: null
                last: null
              results: 2
              totalResults: 2
              page: 1
              totalPages: 1
            message: "Successfully retrieved the resource."

    Blog:
      description: "Return the blog on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    $ref: "#/components/schemas/Blog"
          example:
            success: true
            data:
              uid: 1
              title: "Blog Post"
              slug: "blog-post"
              shortDesc: "A brief description of the blog post"
              image:
                src: "image.jpg"
                alt: "Image for blog post"
              content: This blog will introduce you to the basics...
              createdAt: "2023-11-28T10:00:00Z"
              updatedAt: "2023-11-28T11:00:00Z"
            message: "{fix me; The message will be different based on the methods, Get, Post and Pacth}"

    Events:
      description: "Returns a list of events on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    allOf:
                      - $ref: "#/components/schemas/GetResources"
                      - properties:
                          items:
                            items:
                              $ref: "#/components/schemas/EventItem"
          example:
            success: true
            data:
              items:
                - uid: 1
                  title: "Event 1"
                  shortDesc: "A brief description of the event 1"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
                  startDateTime: "2023-12-01T09:00:00Z"
                  location: "Willowbrook Lane 17, Welford-on-Avon, Warwickshire, CV37 8JA, United Kingdom"
                - uid: 2
                  title: "Event 2"
                  shortDesc: "A brief description of the event 2"
                  startDateTime: "2023-12-08T09:00:00Z"
                  location: "Convention Center"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
              pagination:
                first: 1
                prev: 1
                current: 1
                next: 1
                last: 1
              results: 2
              totalResults: 2
              page: 1
              totalPages: 1
            message: "Successfully retrieved the resource."

    Event:
      description: "Return the event on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    allOf:
                      - $ref: "#/components/schemas/GetResources"
                      - properties:
                          items:
                            $ref: "#/components/schemas/Event"
          example:
            success: true
            data:
              items:
                - uid: 1
                  title: "Event 1"
                  shortDesc: "A brief description of the event 1"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
                  startDateTime: "2023-12-01T09:00:00Z"
                  location: "Willowbrook Lane 17, Welford-on-Avon, Warwickshire, CV37 8JA, United Kingdom"
                - uid: 2
                  title: "Event 2"
                  shortDesc: "A brief description of the event 2"
                  startDateTime: "2023-12-08T09:00:00Z"
                  location: "Convention Center"
                  createdAt: "2023-11-28T10:00:00Z"
                  updatedAt: "2023-11-28T11:00:00Z"
              pagination:
                first: 1
                prev: 1
                current: 1
                next: 1
                last: 1
              results: 2
              totalResults: 2
              page: 1
              totalPages: 1
            message: "{fix me; The message will be different based on the methods, Get, Post and Pacth}"

    Images:
      description: "Returns a list of images on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    allOf:
                      - $ref: "#/components/schemas/GetResources"
                      - properties:
                          items:
                            $ref: "#/components/schemas/ImageItem"
          example:
            success: true
            data:
              items:
                - uid: 1
                  src: "image1.jpg"
                  alt: "Alt text for image 1"
                  createdAt: "2023-11-28T09:00:00Z"
                  updatedAt: "2023-11-28T09:30:00Z"
                - uid: 2
                  src: "image1.jpg"
                  alt: "Alt text for image 1"
                  createdAt: "2023-11-29T08:00:00Z"
                  updatedAt: "2023-11-29T08:45:00Z"
              pagination:
                first: 1
                prev: 1
                current: 1
                next: 1
                last: 1
              results: 2
              totalResults: 2
              page: 1
              totalPages: 1
            message: "Successfully retrieved the resource."

    Image:
      description: "Return the image on success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ContentResponse"
              - properties:
                  data:
                    $ref: "#/components/schemas/Image"
          example:
            success: true
            data:
              uid: 1
              src: "image1.jpg"
              alt: "Alt text for image 1"
              createdAt: "2023-11-28T09:00:00Z"
              updatedAt: "2023-11-28T09:30:00Z"
            message: "{fix me; The message will be different based on the methods, Get, Post and Pacth}"

    SuccessfulDelete:
      description: "The resource has been deleted successfully"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NoContentResponse"
          example:
            success: true
            message: "The resource has been deleted successfully."

    BadRequest:
      description: The request cannot be fulfilled due to bad syntax.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            success: false
            error:
              code: 400
              message: The request cannot be fulfilled due to bad syntax.
              description: A concrete description...

    Unauthorized:
      description: Access is denied.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            success: false
            error:
              code: 401
              message: Access is denied.
              description: A concrete description...

    NotFound:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            success: false
            error:
              code: 404
              message: The requested resource was not found.
              description: A concrete description...

    MethodNotAllowed:
      description: The request method is not supported.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            success: false
            error:
              code: 405
              message: The request method is not supported.
              description: A concrete description...

  schemas:
    ContentResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
        message:
          type: string

    NoContentResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
            description:
              type: string

    GetResources:
      type: object
      properties:
        items:
          type: array
          items: {}
        pagination:
          type: object
          properties:
            first:
              type: integer
            prev:
              type: integer
            current:
              type: integer
            next:
              type: integer
            last:
              type: integer
        results:
          type: integer
        totalResults:
          type: integer
        page:
          type: integer
        totalPages:
          type: integer

    UserItem:
      type: object
      properties:
        uid:
          type: integer
          description: Unique identifier for the user.
        firstName:
          type: string
          description: User's first name.
        lastName:
          nullable: true
          type: string
          description: User's last name.
        email:
          type: string
          format: email
          description: Unique email address for the user.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the user was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the user was last updated.
        loggedInAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the user last logged in.

    BlogItem:
      type: object
      properties:
        uid:
          type: integer
          description: Unique identifier for the blog.
        title:
          type: string
          description: Title of the blog post.
        shortDesc:
          type: string
          description: A brief description of the blog post.
        image:
          nullable: true
          $ref: "#/components/schemas/ImageRef"
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the blog was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the blog was last updated.

    EventItem:
      type: object
      properties:
        uid:
          type: integer
          format: uuid
          description: Unique identifier for the event.
        title:
          type: string
          description: Title of the event.
        shortDesc:
          type: string
          description: Unique SLUG identifying for the event.
        startDateTime:
          type: string
          format: date-time
          description: ISO 8601 representation the start date and time of the event.
        location:
          type: string
          description: Location where the event takes place.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the event was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the event was last updated.

    ImageItem:
      type: object
      properties:
        uid:
          type: integer
          format: uuid
          description: Unique identifier for the image.
        src:
          type: string
          description: Image name with extension.
        alt:
          type: string
          description: Alternate text for the image.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the image was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the image was last updated.

    User:
      type: object
      properties:
        uid:
          type: integer
          description: Unique identifier for the user.
        firstName:
          type: string
          description: User's first name.
        lastName:
          nullable: true
          type: string
          description: User's last name.
        email:
          type: string
          description: Unique email address for the user.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the user was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the user was last updated.
        loggedInAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the user last logged in.

    UserPostBody:
      type: object
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 50
          description: "First name of the user."
          example: "John"
        lastName:
          type: string
          nullable: true
          minLength: 2
          maxLength: 50
          description: "Last name of the user."
          example: "Doe"
        email:
          type: string
          minLength: 5
          maxLength: 100
          description: "Unique email address of the user."
          example: "johndoe@example.com"
      required: [firstName, email]

    UserPatchBody:
      type: object
      properties:
        firstName:
          type: string
          minLength: 2
          maxLength: 50
          description: "First name of the user."
          example: "John"
        lastName:
          type: string
          nullable: true
          minLength: 2
          maxLength: 50
          description: "Last name of the user."
          example: "Doe"
        email:
          type: string
          minLength: 5
          maxLength: 100
          description: "Unique email address of the user."
          example: "johndoe@example.com"
      minProperties: 1

    Blog:
      type: object
      properties:
        uid:
          type: integer
          format: uuid
          description: Unique identifier for the blog.
        title:
          type: string
          description: Title of the blog post.
        slug:
          type: string
          description: Unique SLUG identifier for the blog.
        shortDesc:
          type: string
          description: A brief description of the blog post.
        image:
          nullable: true
          $ref: "#/components/schemas/ImageRef"
          description: Image Referring Object or a null value.
        content:
          type: string
          description: Content of the blog post in Markdown format.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the blog was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the blog was last updated.

    BlogPostBody:
      type: object
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 100
          description: "Title of the blog post."
          example: "Welcome to the world of FLUG!"
        slug:
          type: string
          minLength: 5
          maxLength: 150
          description: "Unique slug in blogs."
          example: "welcome-to-the-world-of-flug"
        shortDesc:
          type: string
          minLength: 145
          maxLength: 155
          description: "Short description of the blog post."
          example: "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
        image:
          type: object
          description: "Image data specified as a data URI scheme, encoded in base64."
          nullable: true
          properties:
            src:
              type: string
              format: uri-base64
              description: "Image data encoded in base64."
              example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
            alt:
              type: string
              description: "Image Alt Text"
              example: "FLUG Logo"
        content:
          type: string
          minLength: 300
          maxLength: 65535
          description: "Content of the blog post in Markdown format."
          example: "This blog will introduce you to the basics..."
      required: [title, slug, shortDesc, content]

    BlogPatchBody:
      type: object
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 100
          description: "Title of the blog post."
          example: "Welcome to the world of FLUG!"
        slug:
          type: string
          minLength: 5
          maxLength: 150
          description: "Unique slug in blogs."
          example: "welcome-to-the-world-of-flug"
        shortDesc:
          type: string
          minLength: 145
          maxLength: 155
          description: "Short description of the blog post."
          example: "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
        image:
          type: object
          description: "Image data specified as a data URI scheme, encoded in base64."
          nullable: true
          properties:
            src:
              type: string
              format: uri-base64
              description: "Image data encoded in base64."
              example: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."
            alt:
              type: string
              description: "Image Alt Text"
              example: "FLUG Logo"
        content:
          type: string
          minLength: 300
          maxLength: 65535
          description: "Content of the blog post in Markdown format."
          example: "This blog will introduce you to the basics..."
      minProperties: 1

    Event:
      type: object
      properties:
        uid:
          type: integer
          format: uuid
          description: Unique identifier for the event.
        title:
          type: string
          description: Title of the event.
        slug:
          type: string
          description: Unique SLUG identifying for the event.
        shortDesc:
          type: string
          description: A brief description of the event.
        startDateTime:
          type: string
          format: date-time
          description: ISO 8601 representation the start date and time of the event.
        endDateTime:
          type: string
          format: date-time
          description: ISO 8601 representation the end date and time of the event.
        location:
          type: string
          description: Location where the event takes place.
        content:
          type: string
          description: Details of the event in Markdown format.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the event was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the event was last updated.

    EventPostBody:
      type: object
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 100
          description: "Title of the event."
          example: "FLUG event!"
        slug:
          type: string
          pattern: "^(?!-)[a-z0-9-]+(?<!-)$"
          minLength: 5
          maxLength: 150
          description: "Unique slug in events."
          example: "flug-event"
        shortDesc:
          type: string
          minLength: 145
          maxLength: 155
          description: "Short description of the event."
          example: "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
        startDateTime:
          type: string
          format: date-time
          description: "The start date and time of the event."
          example: "2023-12-01T09:00:00Z"
        endDateTime:
          type: string
          format: date-time
          description: "The end date and time of the event. Needs to be later than `startDateTime`."
          example: "2023-12-01T11:00:00Z"
        location:
          type: string
          description: "Location where the event takes place."
          example: "Willowbrook Lane 17, Welford-on-Avon, Warwickshire, CV37 8JA, United Kingdom"
        content:
          type: string
          minLength: 300
          maxLength: 65535
          description: "Content of the event in Markdown format."
          example: "This event will introduce you to the basics..."
      required:
        [title, slug, shortDesc, startDateTime, endDateTime, location, content]

    EventPatchBody:
      type: object
      properties:
        title:
          type: string
          minLength: 5
          maxLength: 100
          description: "Title of the event."
          example: "FLUG event!"
        slug:
          type: string
          minLength: 5
          maxLength: 150
          description: "Unique slug in events."
          example: "flug-event"
        shortDesc:
          type: string
          minLength: 145
          maxLength: 155
          description: "Short description of the event."
          example: "A thorough introduction to the FLUG organization and what it means for you and your work with Linux in professional life..."
        startDateTime:
          type: string
          format: date-time
          description: "The start date and time of the event."
          example: "2023-12-01T09:00:00Z"
        endDateTime:
          type: string
          format: date-time
          description: "The end date and time of the event. Need to be later than `startDateTime`."
          example: "2023-12-01T11:00:00Z"
        location:
          type: string
          description: "Location where the event takes place."
          example: "Willowbrook Lane 17, Welford-on-Avon, Warwickshire, CV37 8JA, United Kingdom"
        content:
          type: string
          minLength: 300
          maxLength: 65535
          description: "Content of the event in Markdown format."
          example: "This event will introduce you to the basics..."
      minProperties: 1

    Image:
      type: object
      properties:
        uid:
          type: integer
          format: uuid
          description: Unique identifier for the image.
        src:
          type: string
          description: Image name with extension.
        alt:
          type: string
          description: Alternate text for the image.
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 representation when the image was created.
        updatedAt:
          type: string
          format: date-time
          nullable: true
          description: ISO 8601 representation when the image was last updated.

    ImagePostBody:
      type: object
      properties:
        src:
          type: string
          format: uri-byte
          description: "Data URI scheme, encoded in base64."
          example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..."
        alt:
          type: string
          minLength: 15
          maxLength: 50
          description: "Alternative text description for the image."
          example: "Image Alt Text"
      required: [src, alt]

    ImagePatchBody:
      type: object
      properties:
        src:
          type: string
          format: uri-byte
          description: "Data URI scheme, encoded in base64."
          example: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD..."
        alt:
          type: string
          minLength: 15
          maxLength: 50
          description: "Alternative text description for the image."
          example: "Image Alt Text"
      minProperties: 1

    ImageRef:
      type: object
      properties:
        src:
          type: string
          description: Image name with extension.
        alt:
          type: string
          description: Alternate text for the image.
